/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_physics_box2d_joints_ConstantVolumeJoint */

#ifndef _Included_com_badlogic_gdx_physics_box2d_joints_ConstantVolumeJoint
#define _Included_com_badlogic_gdx_physics_box2d_joints_ConstantVolumeJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_physics_box2d_joints_ConstantVolumeJoint
 * Method:    jniInflate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_joints_ConstantVolumeJoint_jniInflate
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
